import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useDropzone } from "react-dropzone";
import { parse } from "papaparse";
import { useCallback, useState } from "react";
const Home: NextPage = () => {
  // users contains all the data from sqlite / Prisma!
  // Plus its typesafe :D
  const users = trpc.example.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Indigov CSV Reader</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Indigov CSV Reader
        </h1>
        <FileDropZone />

        <div className="flex flex-col items-center justify-center">
          {users?.data?.map((item) => {
            const { email, firstName, lastName, zipcode } = item;
            return (
              <UserCard
                // We want the key to be unique between renders
                key={`userCard-${email}`}
                email={email}
                firstName={firstName}
                lastName={lastName}
                zipcode={zipcode}
              />
            );
          })}
        </div>
      </main>
    </>
  );
};

export default Home;

type UserCardProps = {
  email: string;
  firstName: string;
  lastName: string;
  zipcode: string;
};

const UserCard = ({ email, firstName, lastName, zipcode }: UserCardProps) => {
  return (
    <section className="my-2 flex flex-col justify-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{`${firstName} ${lastName}`}</h2>
      <p className="text-sm text-gray-600">{email}</p>
      <p className="text-sm text-gray-600">{zipcode}</p>
    </section>
  );
};

type User = {
  FirstName: string;
  LastName: string;
  Email: string;
  ZipCode: string;
};

const FileDropZone = () => {
  const [fileData, setFileData] = useState<any>([]);
  const userMutation = trpc.example.createUser.useMutation();

  const saveUser = useCallback(() => {
    // trpc mutation to save to db
    fileData.forEach(async (user: User) => {
      const firstName = user?.FirstName;
      const lastName = user?.LastName;
      const email = user?.Email;
      const zipcode = user?.ZipCode;
      await userMutation.mutate({ firstName, lastName, email, zipcode });
    });
  }, [fileData, userMutation]);

  const onDrop = useCallback(async (acceptedFiles: any) => {
    console.log("DROPPED");
    acceptedFiles.forEach(async (file: any) => {
      const text = await file?.text();
      const result = parse(text, { header: true });
      // Each row should now be the key of the object
      setFileData(result?.data);
    });
  }, []);
  const { getRootProps, getInputProps } = useDropzone({
    onDrop,
    accept: {
      "text/csv": [".csv"],
    },
  });

  return fileData?.length === 0 ? (
    <div
      {...getRootProps()}
      className=" flex  flex-col items-center justify-center border-2 border-dashed border-black p-6"
    >
      <input {...getInputProps()} />
      <span className="my-2">Drag and Drop File here!</span>
      <span className="my-2">Or</span>
      <button className="my-2 rounded-lg bg-purple-600 px-4 py-2 text-white">
        Click to select file
      </button>
    </div>
  ) : (
    <div>
      <span>Here is what you submitted 😄 </span>
      {/* Map over the file and display what we parsed from the file */}
      {fileData.map((item: User) => {
        const firstName = item?.FirstName;
        const lastName = item?.LastName;
        const email = item?.Email;
        const zipcode = item?.ZipCode;

        return (
          <UserCard
            key={email}
            email={email}
            firstName={firstName}
            lastName={lastName}
            zipcode={zipcode}
          />
        );
      })}

      {/* If that looks good allow the user to save and write to the database */}
      <button
        className="py flex items-center justify-center border-2 border-purple-500 bg-purple-300 px-2 text-white opacity-90 hover:opacity-100"
        onClick={saveUser}
      >
        Save
      </button>
    </div>
  );
};
